### ISSUE TITLE
not ok 1 - Device should be in production mode

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-generic#118]
```
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:02:47.507Z][worker-cloud]     # Subtest: SSH authentication test
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:02:47.507Z][worker-cloud]         # Subtest: SSH authentication in production mode
jenkins-leviathan-v2-template-2960-client-1  |             # Setting production mode in config.json...
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:03:18.692Z][worker-cloud]             not ok 1 - Device should be in production mode
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:03:18.692Z][worker-cloud]               ---
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:03:18.692Z][worker-cloud]               found: "error: host error:"
jenkins-leviathan-v2-template-2960-client-1  | [2022-07-16T02:03:18.692Z][worker-cloud]               wanted: "false"
```
https://jenkins.product-os.io/job/leviathan-v2-template/2960/consoleFull
[consoleText.txt](https://github.com/balena-os/balena-generic/files/9132770/consoleText.txt)

**Comment by rcooke-warwick** [comment]
I've seen failures around this test a few times now - where a change to the config.json seemingly isn't being respected. 

We had this attempt at fixing it I think last week: https://github.com/balena-os/meta-balena/commit/916d400456ef2cb58f13c7b8b6e542c23b57e8c2 but it might not have been enough

**Comment by klutchell** [comment]
I don't think we are waiting long enough between these tests, since config changes on slower devices could take a while to populate. Or, as we've seen before, we aren't waiting for config-json.service to be inactive before making config changes.

**Comment by klutchell** [comment]
In this case, we are expecting the change to be instant
```node
				}).then(() => {
					return this.cloud.executeCommandInHostOS(
						`jq -r '.developmentMode' /mnt/boot/config.json`,
						this.balena.uuid
					)
				}).then((actual) => {
					const expected = 'false';
					test.equal(actual, expected, 'Device should be in production mode ');
```

**Comment by klutchell** [comment]
I'm going to rework this test a bit
