### ISSUE TITLE
Compare kernel config between genericx86_64-ext and generic-amd64

### ISSUE THREAD

**Issue by mtoman** [balena-os/balena-generic#20]
The `genericx86_64-ext` has its own `defconfig` based on Ubuntu with some extra changes necessary to boot flasher on a variety of devices while the `generic-amd64` is based on `x86_64_defconfig`. We should unify this as the two device types are fairly similar.

**Comment by jakogut** [comment]
Closed by https://github.com/balena-os/balena-generic/pull/35
