### ISSUE TITLE
Push to Docker Hub?

### ISSUE THREAD

**Issue by shaunco** [balena-os/balena-generic#288]
The last x86 resinOS published to Docker Hub was [2.99.27_rev2-genericx86-64-ext](https://hub.docker.com/layers/resin/resinos/2.99.27_rev2-genericx86-64-ext/images/sha256-801b7fc90f7008a7a930fb2f3331d37edc5b90491355db2f224862761a5c5570?context=explore) - **over a year ago**.

resinOS was renamed to balenaOS [almost 5 years ago](https://blog.balena.io/resin-io-changes-name-to-balena-releases-open-source-edition/).

Is there a plan to start pushing these generic x86-64 and arm64 images to Docker Hub again?
_(asking for https://github.com/balena-os/balenaos-in-container/issues/60 )_

**Comment by klutchell** [comment]
Hey @shaunco , as you noticed we have stopped publishing balenaOS base images to DockerHub.

Instead we are deploying the images as balena apps to our balenaCloud registry, to make better use of our own infrastructure.

While you cannot browse the images as you would with DockerHub, the syntax for pulling is `bh.cr/balena_os/<device_type>/<version>`. Note the `/` between the device type and the version, that's important.

So to pull the latest generic-amd64 image you could do...

```bash
balena os versions generic-amd64
docker pull bh.cr/balena_os/generic-amd64/3.2.9
```

I hope this helps!

**Comment by shaunco** [comment]
Thank you! 

How do I reconcile latest versions for each device type? The various repos (like this one) don't seem to get release tags, and but I can reference the https://github.com/balena-os/balena-generic/blob/master/VERSION file in each repo. Alternatively, if I log into balena-cloud and click "add device", I see the latest version in the "select version" dropdown. However, this repo has a VERSION file that says `3.2.11`, but if I look at balena-cloud that version only seems to be available for `amd64`, while `aarch64` is still at `3.2.9+REV1` (even though it comes from the same repo?).

That is:
`docker pull bh.cr/balena_os/generic-amd64/3.2.11` works
but
`docker pull bh.cr/balena_os/generic-aarch64/3.2.11` fails - despite https://github.com/balena-os/balena-generic/blob/master/VERSION having `3.2.11` in it.

https://www.balena.io/os#download-os seems to align with what balena-cloud shows when I go through the "add device" dialog...

**Comment by shaunco** [comment]
@klutchell - I'm also missing something on the `rev1` versions, as I can't seem to get any variation of:
`docker pull bh.cr/balena_os/generic-aarch64/3.2.9+rev1`
`docker pull bh.cr/balena_os/generic-aarch64/3.2.9-rev1`
`docker pull bh.cr/balena_os/generic-aarch64/3.2.9_rev1`
`docker pull bh.cr/balena_os/generic-aarch64/3.2.9.rev1`
`docker pull bh.cr/balena_os/generic-aarch64/3.2.9rev1`

to work. How is the `+` encoded in the balena container registry, as trying to use a `+` in the image name for a `pull` has docker respond with `invalid reference format`

similarly, I can't list tags in the balena container registry with:
`docker pull bh.cr/balena_os/generic-aarch64/tags`

**Comment by klutchell** [comment]
Hey @shaunco , in order to get the latest release for a device type I would suggest using the [balena CLI](https://docs.balena.io/reference/balena-cli/#os-versions-type) as I did in my example above.

```bash
balena os versions generic-amd64 | head n1
v3.2.9+rev1
```

There is also no need to specify the rev in the image reference, the latest revision will always be pulled automatically. It's covered [briefly in this doc](https://docs.balena.io/learn/develop/blocks/#using-your-block-in-other-projects).

Our registry does not allow listing tags because `balena_os/generic-aarch64` is not the real image path but is translated by a proxy in front of our registry to allow for renaming of apps and orgs. Also each release uses a separate repository, so there is only ever one tag per repository at the moment.
