### ISSUE TITLE
Requests to update to kernel 6.2+ / 6.6 LTS

### ISSUE THREAD

**Issue by mtoman** [balena-os/balena-generic#296]
At this moment the generic DTs are running LTS kernel 6.1, this issue tracks requests for features that come between 6.2 and the next LTS version.

**Comment by xouillet** [comment]
Linux 6.2 brings `rtw88` module, that adds support for USB wifi devices based on Realtek 8822BU chipset. Thoses devices are affordable and very easily sourceable so they are quite common.

Interestingly enough, an out-of-tree driver is provided in BalenaOS for NUC (cf. https://github.com/balena-os/balena-intel/tree/master/layers/meta-balena-genericx86/recipes-kernel/rtl8812bu), but not in generic. But NUC image is still on 5.18 at this time.

Building out-of-tree or backports would work for balenaos, but now that secureboot is available, loading out-of-tree kernel can be painful, so having in-kernel module support for theses USB wifi devices can be a good thing.

**Comment by mtoman** [comment]
6.6 is the new LTS, we should update to that

**Comment by mtoman** [comment]
This is also necessary for 12+ gen Intel iGPUs to work properly with HW acceleration.

**Comment by aiddun** [comment]
Hi, any update on this?

**Comment by floion** [comment]
Hi, created https://github.com/balena-os/balena-generic/pull/456 for this

**Comment by floion** [comment]
Kernel version 6.6 is now available in OS release v6.0.5+rev4
